### ISSUE TITLE
建议不将.idea文件目录及.iml等IDEA配置文件提交，可以添加到.gitignore

### ISSUE THREAD

**Issue by bitlin** [AutoMeter/testplantform#21]
这些文件都会自动生成呢，而且由于不同客户端生成的还不一样，这样子git pull更新会很多文件冲突

**Comment by SeasonFan** [comment]
非常谢谢，已经提交gitignore，欢迎一起交流

**Comment by bitlin** [comment]
项目很优秀呀，膜拜学习。话说，yml配置中的账号密码都是加密的，如果想改成自己的账号密码就有点麻烦了

**Comment by SeasonFan** [comment]
谢谢建议，已经更新部署文档，其中有描述了数据库账号密码的问题
